spring.application.name=AssetTrack

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/asset_track
spring.datasource.username=postgres
spring.datasource.password=dba
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# JWT Secret Configuration
jwt.secret=67556B58703273357638792F423F4528482B4D6251655468576D5A7134743777
jwt.expirationMs=3600000

# Dummy user credentials for now
app.user.username=admin
app.user.password=password
