spring.application.name=AssetTrack

# Database Configuration (H2 File Mode)
spring.datasource.url=jdbc:h2:file:./data/asset_track_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Secret Configuration
jwt.secret=67556B58703273357638792F423F4528482B4D6251655468576D5A7134743777
jwt.expirationMs=3600000

# Dummy user credentials for login
app.user.username=admin
app.user.password=password
